-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 21:18:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uas_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uas_db` ;

-- -----------------------------------------------------
-- Schema uas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uas_db` ;
USE `uas_db` ;

-- -----------------------------------------------------
-- Table `uas_db`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`user_type` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_role_UNIQUE` (`user_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`user_status` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`user_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`user` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `passport_code` VARCHAR(20) NOT NULL,
  `user_type_id` INT NOT NULL,
  `user_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `passport_code_UNIQUE` (`passport_code` ASC) VISIBLE,
  INDEX `fk_user_user_type_idx` (`user_type_id` ASC) VISIBLE,
  INDEX `fk_user_user_status1_idx` (`user_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `uas_db`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_status1`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `uas_db`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`subject` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`exam` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exam_subject1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_exam_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `uas_db`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`user_exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`user_exam` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`user_exam` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `exam_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exam_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_exam_has_user_exam1_idx` (`exam_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_user_exam_combination` (`user_id` ASC, `exam_id` ASC) INVISIBLE,
  CONSTRAINT `fk_exam_has_user_exam1`
    FOREIGN KEY (`exam_id`)
    REFERENCES `uas_db`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `uas_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`grade` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`grade` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `subject_id` INT NOT NULL,
  `result` INT NOT NULL,
  INDEX `fk_grade_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_grade_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_user_subject_combination` (`user_id` ASC, `subject_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_grade_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `uas_db`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grade_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `uas_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`university`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`university` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`university` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`specialty` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`specialty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`education_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`education_option` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`education_option` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `university_id` INT NOT NULL,
  `specialty_id` INT NOT NULL,
  `student_limit` INT NOT NULL,
  INDEX `fk_university_has_specialty_specialty1_idx` (`specialty_id` ASC) VISIBLE,
  INDEX `fk_university_has_specialty_university1_idx` (`university_id` ASC) INVISIBLE,
  UNIQUE INDEX `unique_speciality_university_combination` (`university_id` ASC, `specialty_id` ASC) INVISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_university_has_specialty_university1`
    FOREIGN KEY (`university_id`)
    REFERENCES `uas_db`.`university` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_university_has_specialty_specialty1`
    FOREIGN KEY (`specialty_id`)
    REFERENCES `uas_db`.`specialty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`specialty_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`specialty_subject` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`specialty_subject` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `specialty_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_has_specialty_specialty1_idx` (`specialty_id` ASC) VISIBLE,
  INDEX `fk_subject_has_specialty_subject1_idx` (`subject_id` ASC) VISIBLE,
  UNIQUE INDEX `unique_speciality_subject_combination` (`subject_id` ASC, `specialty_id` ASC) VISIBLE,
  CONSTRAINT `fk_subject_has_specialty_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `uas_db`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_has_specialty_specialty1`
    FOREIGN KEY (`specialty_id`)
    REFERENCES `uas_db`.`specialty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uas_db`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uas_db`.`request` ;

CREATE TABLE IF NOT EXISTS `uas_db`.`request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `education_option_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) INVISIBLE,
  INDEX `fk_request_education_option1_idx` (`education_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `uas_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_education_option1`
    FOREIGN KEY (`education_option_id`)
    REFERENCES `uas_db`.`education_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
